port: "8080"
rest:
  github:
    url: "https://api.github.com"
    repos:
      search: "/search/repositories"
      get: "/repos/{owner}/{repo}"
    releases:
      list: "/repos/{owner}/{repo}/releases"
      last: "/repos/{owner}/{repo}/releases/latest"
      get_by_tag: "/repos/{owner}/{repo}/releases/tags/{tag}"
